/*
 * QuickStart DataHub API
 * This is a sample of a QuickStart DataHub Swagger doucment defining endpoints to be mocked
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marklogic.hub.client.api;


import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for FlowsApi
 */
//@Ignore
public class FlowsApiTest {

    private final FlowsApi api = new FlowsApi();

    
    /**
     * Create flow
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFlowTest() {
        
        api.createFlow();

        // TODO: test validations
    }
    
    /**
     * Create Step for a Flow
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFlowStepTest() {
        
        String flowId = null;
        
        api.createFlowStep(flowId);

        // TODO: test validations
    }
    
    /**
     * Delete flow by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFlowTest() {
        
        String flowId = null;
        
        api.deleteFlow(flowId);

        // TODO: test validations
    }
    
    /**
     * Delete a Flow&#x27;s step by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFlowStepTest() {
        
        String flowId = null;
        
        String stepId = null;
        
        api.deleteFlowStep(flowId, stepId);

        // TODO: test validations
    }
    
    /**
     * Find flow by Id
     *
     * ....
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowTest() {
        
        String flowId = null;
        flowId = "rahul";
        String s = api.getFlow(flowId);
        System.out.println(s);

        // TODO: test validations
    }
    
    /**
     * Find all Steps accociated with a Flow
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowStepsTest() {
        
        String flowId = null;
        
        api.getFlowSteps(flowId);

        // TODO: test validations
    }
    
    /**
     * Returns all flows
     *
     * Returns all flows
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowsTest() {
        
        api.getFlows();

        // TODO: test validations
    }
    
    /**
     * Update flow by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFlowTest() {
        
        String flowId = null;
        
        api.updateFlow(flowId);

        // TODO: test validations
    }
    
    /**
     * Update a Flow&#x27;s step by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFlowStepTest() {
        
        String flowId = null;
        
        String stepId = null;
        
        api.updateFlowStep(flowId, stepId);

        // TODO: test validations
    }
    
}
