/*
 * QuickStart DataHub API
 * This is a sample of a QuickStart DataHub Swagger doucment defining endpoints to be mocked
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marklogic.hub.client.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CustomHook
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2019-02-22T15:51:23.383-08:00[America/Los_Angeles]")
public class CustomHook {

  
  @JsonProperty("module")
  private String module = null;
  
  
  @JsonProperty("parameters")
  private Object parameters = null;
  
  
  @JsonProperty("user")
  private String user = null;
  
  
  @JsonProperty("runBefore")
  private Boolean runBefore = null;
  
  public CustomHook module(String module) {
    this.module = module;
    return this;
  }

  
  /**
  * Get module
  * @return module
  **/
  @ApiModelProperty(value = "")
  public String getModule() {
    return module;
  }
  public void setModule(String module) {
    this.module = module;
  }
  
  public CustomHook parameters(Object parameters) {
    this.parameters = parameters;
    return this;
  }

  
  /**
  * Get parameters
  * @return parameters
  **/
  @ApiModelProperty(value = "")
  public Object getParameters() {
    return parameters;
  }
  public void setParameters(Object parameters) {
    this.parameters = parameters;
  }
  
  public CustomHook user(String user) {
    this.user = user;
    return this;
  }

  
  /**
  * Get user
  * @return user
  **/
  @ApiModelProperty(value = "")
  public String getUser() {
    return user;
  }
  public void setUser(String user) {
    this.user = user;
  }
  
  public CustomHook runBefore(Boolean runBefore) {
    this.runBefore = runBefore;
    return this;
  }

  
  /**
  * Get runBefore
  * @return runBefore
  **/
  @ApiModelProperty(value = "")
  public Boolean isRunBefore() {
    return runBefore;
  }
  public void setRunBefore(Boolean runBefore) {
    this.runBefore = runBefore;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomHook customHook = (CustomHook) o;
    return Objects.equals(this.module, customHook.module) &&
        Objects.equals(this.parameters, customHook.parameters) &&
        Objects.equals(this.user, customHook.user) &&
        Objects.equals(this.runBefore, customHook.runBefore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(module, parameters, user, runBefore);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomHook {\n");
    
    sb.append("    module: ").append(toIndentedString(module)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    runBefore: ").append(toIndentedString(runBefore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



